package main
import("crypto/subtle";"encoding/json";"io";"net/http";"os";"os/exec";"strings";"time")
type manage struct{WG json.RawMessage `json:"wireguard"`;NetVersion string `json:"net_version"`;DDNSVersion string `json:"ddns_version"`;DDNSLoop string `json:"ddns_loop"`;Control bool `json:"control_enabled"`}
func run(a ...string)string{c:=exec.Command(a[0],a[1:]...);b,e:=c.CombinedOutput();if e!=nil{return "error"};return strings.TrimSpace(string(b))}
func ver(p string)string{o:=run("opkg","status",p);for _,l:=range strings.Split(o,"\n"){if strings.HasPrefix(l,"Version: "){return strings.TrimSpace(strings.TrimPrefix(l,"Version: "))}};return "unknown"}
func loop()string{o:=run("/opt/sr1010-cf-ddns/health.sh");for _,l:=range strings.Split(o,"\n"){if strings.HasPrefix(l,"loop="){return strings.TrimPrefix(l,"loop=")}};return "unknown"}
func status(w http.ResponseWriter,r *http.Request){b,_:=os.ReadFile("/opt/sr1010-net-runtime/state/dashboard.json");if !json.Valid(b){b=[]byte(`{"running":false}`)};_,e:=os.Stat("/opt/sr1010-net-runtime/config/dashboard.token");w.Header().Set("Content-Type","application/json");json.NewEncoder(w).Encode(manage{b,ver("sr1010-net-runtime"),ver("sr1010-cf-ddns"),loop(),e==nil})}
var acts=map[string][]string{"net-backup":{"/opt/sr1010-net-runtime/backup.sh"},"ddns-backup":{"/opt/sr1010-cf-ddns/backup.sh"},"net-start":{"/opt/sr1010-net-runtime/start.sh"},"net-stop":{"/opt/sr1010-net-runtime/stop.sh"},"ddns-start":{"/opt/sr1010-cf-ddns/start.sh"},"ddns-stop":{"/opt/sr1010-cf-ddns/stop.sh"}}
func action(w http.ResponseWriter,r *http.Request){if r.Method!="POST"{http.Error(w,"method",405);return};t,_:=os.ReadFile("/opt/sr1010-net-runtime/config/dashboard.token");got:=r.Header.Get("X-SR1010-Token");want:=strings.TrimSpace(string(t));if want==""||len(got)!=len(want)||subtle.ConstantTimeCompare([]byte(got),[]byte(want))!=1{http.Error(w,"unauthorized",401);return};b,_:=io.ReadAll(io.LimitReader(r.Body,128));a:=strings.TrimSpace(string(b));cmd,ok:=acts[a];if !ok{http.Error(w,"bad action",400);return};o:=run(cmd...);w.Header().Set("Content-Type","application/json");json.NewEncoder(w).Encode(map[string]string{"action":a,"result":o})}
const page=`<!doctype html><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>SR1010 管理</title><style>body{background:#0b1220;color:#dbeafe;font:15px system-ui;margin:0}main{max-width:900px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px}.card{background:#152238;border:1px solid #263b5b;border-radius:14px;padding:17px}.v{font-size:22px;font-weight:700;color:#67e8f9}.ok{color:#4ade80}.bad{color:#fb7185}button,input{margin:5px;padding:9px;border-radius:8px;border:1px solid #385276;background:#172943;color:#fff}</style><main><h1>SR1010 插件管理</h1><div class=grid><div class=card>WireGuard<div class=v id=wg>读取中</div></div><div class=card>DDNS<div class=v id=ddns>读取中</div></div><div class=card>net-runtime<div class=v id=nv>—</div></div><div class=card>cf-ddns<div class=v id=dv>—</div></div></div><h2>受保护操作</h2><div class=card><input id=tok type=password placeholder="管理令牌"><button onclick="save()">保存到本次会话</button><br><button onclick="act('net-backup')">备份 WireGuard</button><button onclick="act('ddns-backup')">备份 DDNS</button><button onclick="act('net-start')">启动 WireGuard</button><button onclick="act('ddns-start')">启动 DDNS</button><button onclick="act('ddns-stop')">停止 DDNS</button><pre id=out></pre></div></main><script>tok.value=sessionStorage.sr1010Token||'';function save(){sessionStorage.sr1010Token=tok.value}async function load(){let x=await fetch('/manage.json?'+Date.now()).then(r=>r.json());wg.textContent=x.wireguard.running?'运行中':'异常';wg.className='v '+(x.wireguard.running?'ok':'bad');ddns.textContent=x.ddns_loop;ddns.className='v '+(x.ddns_loop==='running'?'ok':'bad');nv.textContent=x.net_version;dv.textContent=x.ddns_version}async function act(a){save();let r=await fetch('/action',{method:'POST',headers:{'X-SR1010-Token':tok.value},body:a});out.textContent=r.status+' '+await r.text();setTimeout(load,1500)}load();setInterval(load,5000)</script>`
func main(){m:=http.NewServeMux();m.HandleFunc("/",func(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");io.WriteString(w,page)});m.HandleFunc("/manage.json",status);m.HandleFunc("/action",action);a:=os.Getenv("DASHBOARD_LISTEN");if a==""{a="10.77.0.1:51889"};s:=&http.Server{Addr:a,Handler:m,ReadHeaderTimeout:4*time.Second};s.ListenAndServe()}
